# Generated by Django 5.2.9 on 2025-12-04 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id_dept', models.AutoField(primary_key=True, serialize=False)),
                ('nama_dept', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
                'db_table': 'm_dept',
            },
        ),
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id_lowongan', models.AutoField(primary_key=True, serialize=False)),
                ('posisi', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=512)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magang.departement')),
            ],
            options={
                'verbose_name': 'Lowongan',
                'verbose_name_plural': 'Lowongan',
                'db_table': 'magang_table',
                'ordering': ['tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Pendaftar',
            fields=[
                ('id_pendaftar', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('dob', models.DateField(verbose_name='Tanggal Lahir')),
                ('address', models.TextField()),
                ('no_telp', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('path_cv', models.FileField(upload_to='cv/')),
                ('ipk', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lowongan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftar', to='magang.lowongan')),
            ],
            options={
                'verbose_name': 'Pendaftar',
                'verbose_name_plural': 'Pendaftar',
                'db_table': 'pendaftar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransaksiPendaftaran',
            fields=[
                ('id_transaksi_pendaftaran', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lowongan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_pendaftaran', to='magang.lowongan')),
                ('pendaftar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_pendaftaran', to='magang.pendaftar')),
            ],
            options={
                'verbose_name': 'Transaksi Pendaftaran',
                'verbose_name_plural': 'Transaksi Pendaftaran',
                'db_table': 't_pendaftaran_magang',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lowongan',
            index=models.Index(fields=['tanggal_mulai', 'departement'], name='magang_tabl_tanggal_ed4cd1_idx'),
        ),
    ]
